language: c
os: windows
compiler:
  - gcc

#env:
  3global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   #- secure: "TdSvCprPeAUbYYEoZDPocAjOImCbi05o2GLLEdiGQYmLtR7I3qx2MeQ7LjeveVqD0AzS+eAxL+OSjcBS5DA4gXGOVJqQAfclJLJ57MafdoTVzOxGsfqHcyKDo3L3N8nD3AbICeFS+foeCX22bqf9iZiEp0MmxYQ7DvFlc+jCqGk="
   
addons:
  coverity_scan:
    project:
      name: "requizm/cs2d_vscode"
      description: "Your project description here"
    notification_email: mehmet41650@gmail.com
    build_command_prepend: "./configure"
    build_command: "make"
    branch_pattern: master


    
script:
  - make  
