language: c
os: windows
compiler:
- gcc
addons:
  coverity_scan:
    project:
      name: requizm/cs2d_vscode
      description: Your project description here
    notification_email: mehmet416500@hotmail.com
    build_command_prepend: "./configure"
    build_command: make
    branch_pattern: master
script:
- make
before_install:
- openssl aes-256-cbc -K $encrypted_288b5c217884_key -iv $encrypted_288b5c217884_iv
  -in github_deploy_key.enc -out github_deploy_key -d
