language: cpp
os: windows
compiler: gcc

addons:
  coverity_scan:
    project:
      name: "requizm/cs2d_vscode"
      description: <Your project description here>
    notification_email: mehmet41650@gmail.com
    build_command_prepend: ./configure
    build_command: 
    - mkdir build
    - cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" -B build/
    - cd build
    - mingw32-make
    branch_pattern: master

script:
- mkdir build
- cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" -B build/
- cd build
- mingw32-make
