language: cpp
os: windows
compiler: gcc
script:
- mingw32-make
env:
  global:
    secure: o+b3/oodEr7fFJkz1AlwLY30QKwO8RaiCYrtT+yc9YK134LH+Zj1FTxoFat3nUybekw+b1b8gvYY+YLiGAoqZuZ9Nok9vzC6opSwBJRNluX311ROr1SUnD6Ih9h8sitduVCWDhA8/2k2DPlGRHTaNt/3uSxGZAnMQ/H9KYk52c92wcoBocGHKeQuPjmD/jvWejEN+V90/r7YEsL7E1wINbk8bVjgIgNbjfZTpRzoE7e20M1vaEdhHypCzE4JUu29YsNsl+rczq3b6LPekHDxT2dw+CBkAhTVjVyjgYVSVCJVvkXPzNA5jfTsJRwmo16nNYts+KIjMZYOaf+63LAppM681GG1dP/vLg1mwtVxK2MqLinLDocFniNes3jClH5YGIj2q9bNE0uQRfbxrqlfsn/x1/5FQqsQH/3jb347pGXjTOMTuGG0pejwzMySSTO3+fuDQemy/3c3sCvIDlfzDPAI1TtB+JbZz0rv2Jhql2VLMa2dBlVCInwo/vBYAnlvQmQH75E6Ikm1SvtgFVPLUb1Mb7PK3Gho1Kuefxt+45WogfWUy6GgjTtVHhx1osRM93iHFRXGsR4hb8QUfeETZWHtTUnQapz1jkp3NZvwlFWgUxEyB8xMKfyxS+wKQPMfivQXtvspoCirqtTRnA3QXiJ1tPEc+QdttkABlxn4hi8=

#before_install:
#- mkdir build
#- cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" -B build/
#- cd build